#!/bin/sh

if [ "$1" != "in" ] && [ "$1" != "out" ]; then
    echo "please write \"zoom in\" or \"zoom out\""
    exit 2
fi

WM_SIZE_OUTPUT=$(wm size)
WM_SIZE_RESOLUTION=${WM_SIZE_OUTPUT##*:}
CHROMECAST_RESOLUTION=$(echo "$WM_SIZE_RESOLUTION" | tr -d '\n[:space:]')

if [[ $CHROMECAST_RESOLUTION == *"1280x720"* ]]; then
    if [ "$1" == "in" ]; then
        wm density 213
    elif [ "$1" == "out" ]; then
        wm density 192
    fi

elif [[ $CHROMECAST_RESOLUTION == *"1366x768"* ]]; then
    # for zoom out: wm density 204
    echo -e "Resolution not yet supported by Chromecast"

elif [[ $CHROMECAST_RESOLUTION == *"1920x1080"* ]]; then
    if [ "$1" == "in" ]; then
        wm density 320
    elif [ "$1" == "out" ]; then
        wm density 288
    fi

elif [[ $CHROMECAST_RESOLUTION == *"2560x1440"* ]]; then
    # for zoom out: wm density 384
    echo -e "Resolution not yet supported by Chromecast"

elif [[ $CHROMECAST_RESOLUTION == *"3840x2160"* ]]; then
    # for zoom out: wm density 576
    echo -e "Resolution not yet supported by Chromecast"

else
    echo -e "Error in obtaining resolution"
    exit 2
fi

echo "Done"
